export const theme = {
  SegmentedControlBorderRadius: 16,
  SegmentedControlPadding: 4,
  SegmentedControlBackgroundColor: '#eee',
  SegmentedControlItemBackgroundColor: 'transparent',
  SegmentedControlItemBackgroundColorPressed: '#DBDBDB',
  SegmentedControlItemBackgroundColorActive: 'white',
  SegmentedControlItemBackgroundColorActivePressed: '#FFF7F2',
  SegmentedControlItemBorderRadius: 12,
  SegmentedControlItemPadding: 8,
  SegmentedControlItemGap: 4,
  SegmentedControlItemTextFontSize: 16,
  SegmentedControlItemTextTextAlign: 'center',
  SegmentedControlItemTextColor: '#3B3B3B',
  SegmentedControlItemTextColorActive: '#E36414',
} as const;
