export const theme = {
  SegmentedControlBorderRadius: 16,
  SegmentedControlPadding: 4,
  SegmentedControlGap: 4,
  SegmentedControlBackgroundColor: '#eee',
  SegmentedControlItemBackgroundColor: '#eee',
  SegmentedControlItemBackgroundColorPressed: '#DBDBDB',
  SegmentedControlItemBackgroundColorSelected: 'white',
  SegmentedControlItemBackgroundColorSelectedPressed: '#FFF7F2',
  SegmentedControlItemBorderRadius: 12,
  SegmentedControlItemPadding: 8,
  SegmentedControlItemTextFontSize: 16,
  SegmentedControlItemTextTextAlign: 'center',
  SegmentedControlItemTextColor: '#3B3B3B',
  SegmentedControlItemTextColorSelected: '#E36414',
  SegmentedControlItemAnimationDuration: 300,
} as const;
